---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.cantaloupe.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: cantaloupe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cantaloupe.storage.size }}
  {{- if .Values.cantaloupe.storage.className }}
  storageClassName: "{{ .Values.cantaloupe.storage.ClassName }}"
  {{- end }}
