---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fcrepo-env.name" . }}
data:
  MYSQL_PASSWORD: {{ .Values.env.secret.MYSQL_PASSWORD | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.env.secret.MYSQL_PASSWORD | b64enc }}
  JAVA_OPTS: {{ printf "-Dfcrepo.modeshape.configuration=\"classpath:/config/jdbc-mysql/repository.json\" -Dfcrepo.mysql.host=\"%s\" -Dfcrepo.mysql.username=\"%s\" -Dfcrepo.mysql.password=\"%s\" -Dfcrepo.object.directory=\"/data/objects\" -Dfcrepo.binary.directory=\"/data/binaries\"" ( include "app.mysql.name" . ) .Values.env.configmap.MYSQL_USER .Values.env.secret.MYSQL_PASSWORD | b64enc }}

