---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fcrepo-env.name" . }}
data:
  MYSQL_USER: {{ .Values.env.configmap.MYSQL_USER }}
  MYSQL_DATABASE: {{ .Values.env.configmap.FC_DATABASE_NAME }}
