---
#-------------------
# M3 Metadata Model
#-------------------

# ESSI Sample Profile (see https://github.com/samvera-labs/houndstooth/tree/context)

m3_version: "1.0.beta2"

# Administrative information about the profile/model

profile:
  responsibility: https://indiana.edu/
  responsibility_statement: Indiana University
  date_modified: "2019-07-28"
  type: concept
  version: 0.1

# Class Definitions

classes:
  FlexibleMetadata:
    display_label: "Flexible Metadata Example"
    contexts:
      - "flexible_context"

contexts:
  flexible_context:
    display_label: "Flexible Metadata Example"

# Property Definitions

properties:

  title:
    display_label: 
      default: "Title"
      FlexibleMetadata: "Title for Work Type"
      flexible_context: "Title in Context"
    property_uri: http://purl.org/dc/terms/title
    available_on:
      class:
        - FlexibleMetadata
      context:
        - flexible_context
    cardinality:
      minimum: 1
    indexing: [
      "_tesim",
      "_ssm"
    ]

