name: Docker Image CI Test Branch

on:
  push:
    branches: [ test-** ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get branch name
      id: get_branch
      run: echo ::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF:11})
    - name: Build and push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: iublibtech/essi
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
        buildargs: SOURCE_COMMIT
        tags: "test,${{ env.BRANCH_NAME }}"
      env: 
        SOURCE_COMMIT: ${{ github.sha }}
